/* eslint-disable */
// @ts-nocheck
// This file is auto generated by thrift_parser.

import * as a from './a';

export interface GetDataReq {
  /**
   * 这是单行注释
   *
   * 这也是单行注释
   */
  parameters: string;
  /** 这是多行注释 */
  query_status: number;
  money: number;
  is_ok: boolean;
  kvs?: Record<a.A, string>;
  a_list: Array<a.A>;
  item_type: ItemType;
}

export interface GetDataRes {
  body_status: number;
  msg: string;
}

export enum ItemType {
  /** 未知 */
  Unknown = 0,
  /** 普通 */
  Normal = 1,
  /** 特别 */
  Special = 2,
}

type _Options = any;

let urlPrefix = '';
export function setUrlPrefix(prefix: string) {
  urlPrefix = prefix;
}

/** 获取数据 */
export function GetData(req: GetDataReq, options: _Options): Promise<GetDataRes> {
  const query = new URLSearchParams(req).toString();
  const url = `${urlPrefix}/api/get-data?${query}`;
  return fetch(url, { method: 'GET' }, options);
}
